### ISSUE TITLE
Constraint file for the OLED IP

### ISSUE THREAD

**Issue by AlexDaniel** [karljans/SoC_Design#1]
``oled_constraints.xdc`` file was removed in e32a7ae4af250c59113cc6d9fb836020ec56d170.

It seems that the file is still needed. At least, in our configuration the bitstream generation fails because of the lack of constraints for the related pins. It could be that there is something wrong with our configuration, but I thought that I'd create an issue in case somebody has a problem with it too.

**Comment by karljans** [comment]
Added the constraints file back. Closing issue.
